### ISSUE TITLE
Order of the questions in the surveys are shuffled in the csv file

### ISSUE THREAD

**Issue by TuomasA** [CxAalto/koota-server#17]
This shuffling could be removed because it makes survey files harder to use

**Comment by rkdarst** [comment]
This could be because
a) We shuffle the questions in some of the surveys
b) dictionaries are unordered, and answers are stored in dictionaries

The real issues is probably (b).  I probably shouldn't have used dictionaries here, but the order is not always the same each time.

The options are:
a) sort by the `order` column
b) sort by the `id` column

the `id` column does not (for our current project) have a good semantic meaning (it is number-group, not group-number).

So, I will sort by the `order` column.  The questions can still have a different order if they are presented in a different order at different times.  Is this ok?

**Comment by rkdarst** [comment]
The live server should now shuffle by the `order` column (within any one set of answers).  Can you confirm and then close issues if everything works?

Commit 3c8983c

**Comment by TuomasA** [comment]
Yep, this helps!

**Comment by rkdarst** [comment]
Closing issue then.
